# This is a basic workflow to help you get started with Actions

name: Generate updated JavaDoc

env:
  JAVA_VERSION: 13

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # setup jdk
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: $JAVA_VERSION
      # Runs a single command using the runners shell
      - name: Generate the new docks
        run: javadoc -private -splitindex -author -d docs
        
      - name: Update the docks in the git repo
        uses: test-room-7/action-update-file@v1
        with:
          file-path: docs/*
          commit-msg: Update java doc
          github-token: ${{ secrets.GITHUB_TOKEN }}
